### ISSUE TITLE
- is valid in IDENTIFIER

### ISSUE THREAD

**Issue by pschipitsch** [sikula/ruby-hcl#6]
I get this error:

``` js
Racc::ParseError: parse error found on value: -
    from parse.y:139:in `on_error'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb:258:in `_racc_do_parse_c'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/racc/parser.rb:258:in `do_parse'
    from parse.y:145:in `parse'
    from (irb):2
    from /usr/bin/irb:12:in `<main>'
```

when parsing the following:

``` js
variable "ami_id" {
  default = {
    us-east-1 = "ami-fce3c696"
    us-west-1 = "ami-06116566"
    us-west-2 = "ami-9abea4fb"
  }
}

provider "aws" {
    region = "us-west-1"
}

resource "aws_instance" "web" {
    ami = "${lookup(var.ami_id, "us-west-1")}"
    instance_type = "t2.micro"
    tags {
        Name = "HelloWorld"
    }
}
```

This parses without issue:

``` js
variable "ami_id" {
  default = {
    "us-east-1" = "ami-fce3c696"
    "us-west-1" = "ami-06116566"
    "us-west-2" = "ami-9abea4fb"
  }
}

provider "aws" {
    region = "us-west-1"
}

resource "aws_instance" "web" {
    ami = "${lookup(var.ami_id, "us-west-1")}"
    instance_type = "t2.micro"
    tags {
        Name = "HelloWorld"
    }
}
```

Thanks!

**Comment by pschipitsch** [comment]
#7
